remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
title: "Delight"
description: An open source component-oriented UI framework for Unity
kramdown:
  parse_block_html: true

# Aux links for the upper right navigation
aux_links:
    "Unity Asset Store":
      - "//assetstore.unity.com/packages/slug/150494"
    "GitHub":
      - "//github.com/delight-dev/Delight"
    "Chat":
      - "//gitter.im/DelightChat/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link"

plugins:
  - jekyll-seo-tag

