remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
title: "Delight"
description: Delight is an open source component-oriented framework for Unity, mainly centered around creating user-interface components that can easily be extended, combined and shared using a text based declarative design language (similar to HTML).
kramdown:
  parse_block_html: true

# Aux links for the upper right navigation
aux_links:
    "GitHub":
      - "//github.com/delight-dev/Delight"
    "Chat":
      - "//gitter.im/DelightChat/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link"

logo: assets/css/logo-small.jpg

plugins:
  - jekyll-seo-tag

ga_tracking: UA-144203074-1
