remote_theme: pmarsceill/just-the-docs
search_enabled: true
title: "Delight"
description: Delight is an open source component-oriented framework for Unity, mainly centered around creating user-interface components that can easily be extended, combined and shared using a text based declarative design language (similar to HTML).
kramdown:
  parse_block_html: true

# Aux links for the upper right navigation
aux_links:
    'Asset Store&nbsp;&nbsp; <i style="font-size:2.0em;" class="fab fa-unity"></i>':
      - "https://assetstore.unity.com/packages/slug/150494"
    'GitHub&nbsp;&nbsp; <i style="font-size:2.0em;" class="fab fa-github"></i>':
      - "//github.com/delight-dev/Delight"
    'Chat&nbsp;&nbsp; <i style="font-size:2.0em;" class="fab fa-gitter"></i>':
      - "//gitter.im/DelightChat/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link"
    'Sponsor&nbsp;&nbsp; <i style="font-size:2.0em;" class="fas fa-heart"></i>':
      - "https://github.com/sponsors/delight-dev"

logo: "/assets/images/logotype-small.png"

plugins:
  - jekyll-seo-tag

ga_tracking: UA-144203074-1
